if(EXISTS "/home/nikita/Desktop/TREEEE/cmake-example-repo/mybuild/example_tests[1]_tests.cmake")
  include("/home/nikita/Desktop/TREEEE/cmake-example-repo/mybuild/example_tests[1]_tests.cmake")
else()
  add_test(example_tests_NOT_BUILT example_tests_NOT_BUILT)
endif()
